[package]
name = "ismp-beefy"
version = "0.1.0"
edition = "2021"
authors = ["Polytope Labs <hello@polytope.technology>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# crates.io
serde = { version = "1.0.136", features = ["derive"], optional = true }
codec = { package = "parity-scale-codec", version = "3.2.2", default-features = false, features = ["derive"] }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
hex-literal = "0.4.1"
primitive-types = { version = "0.12.1", default-features = false }
log = { version = "0.4.17", default-features = false }
anyhow = { version = "1.0.75", default-features = false }
sp-core = {version = "27.0.0", default-features = false }
frame-support = { default-features = false, workspace = true }
frame-system = { default-features = false, workspace = true }
sp-runtime = { default-features = false, workspace = true }

#local
beefy-verifier-primitives = {path = "../../../consensus/beefy/primitives", default-features = false}
beefy-prover = {path = "../../../consensus/beefy/prover"}
ismp = { path = "../../core", default-features = false }
pallet-ismp = { path = "../../pallet", default-features = false }

substrate-state-machine = { path = "../../pallet/state-machine", default-features = false }


[features]
default = ["std"]
std = [
    "log/std",
    "anyhow/std",
    "sp-core/std",
    "codec/std",
    "scale-info/std",
    "frame-system/std",
    "frame-support/std",
    "sp-runtime/std",
    "pallet-ismp/std",
    "ismp/std",
    "serde",
    "beefy-verifier-primitives/std",
    "substrate-state-machine/std"
    
]
